service: backoffice-api
frameworkVersion: '^3.40.0'
configValidationMode: error

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  timeout: 6 # seconds
  memorySize: 128 # MB
  environment:
    NODE_OPTIONS: --enable-source-maps
  stackTags:
    project: bliss
    service: backoffice-api
  tags:
    project: bliss
    service: backoffice-api
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    useInProcess: true

functions:
  getAllTickets:
    handler: src/handlers/tickets-handler.handleGetAllTickets
    events:
      - httpApi:
          path: /requests
          method: get
  getTicket:
    handler: src/handlers/tickets-handler.handleGetTicket
    events:
      - httpApi:
          path: /requests/{id}
          method: get
  createTicket:
    handler: src/handlers/tickets-handler.handleCreateTicket
    events:
      - httpApi:
          path: /requests
          method: post
